version: 2.1

orbs:
  deployment-tracking: circleci/deployment-tracking@0.1.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - deployment-tracking/record_deployment:
          component: "circleci-mcp-preview-app"
          environment: "production"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - deploy:
          requires:
            - say-hello
